/**
 * Bibel Atlas — master SVG + global locations registry
 *
 * One source of truth for bible-relevant geography. Each timeline page crops
 * to its region via viewBox, references locations by global ID.
 *
 * Coordinate system: viewBox 0 0 1000 540
 *   Projection: x = (lon - 22) * 35.71, y = (39 - lat) * 36
 *   This is approximate equirectangular — fine for stylized rendering.
 *
 * Adding a location: pick lat/lon, project to (x, y), add to LOCATIONS.
 * Adding a page: include this script, set cfg.map = { atlas: BibelAtlas, viewBox: "..." },
 *   reference locations by id in each phase's `locations: []` array.
 */
(function (global) {

  // LOCATIONS data lives in maps/locations.json (source) and maps/locations.js
  // (auto-generated by scripts/build-data.js). Run `npm run build` after edits.
  const LOCATIONS = (typeof window !== "undefined" && window.__BIBEL_LOCATIONS) || {};
  if (Object.keys(LOCATIONS).length === 0) {
    console.warn("[BibelAtlas] No locations loaded. Did you include maps/locations.js before bibel-atlas.js?");
  }

  // SVG geography — coastlines, water, rivers, region labels.
  // Coordinates use the projection: x = (lon - 22) * 35.71, y = (39 - lat) * 36.
  // So Egypt N coast (lat ~31.2) is at y ≈ 281, Anatolia S coast (lat ~36.5) at y ≈ 90.
  const GEO_SVG = `
    <rect class="land" x="0" y="0" width="1000" height="540" />

    <!-- ========== MEDITERRANEAN ========== -->
    <!-- Naturalistic horizontal blob.
         Levant E coast aligned to real geography:
           Antakya (506,101), Beirut (482,184), Tyre (471,206), Haifa (464,222),
           Jaffa (456,249), Gaza area (450,270), Sinai NE (455,275). -->
    <path class="water" d="
      M 0,70
      C 30,72 80,75 130,78
      C 175,82 215,90 250,95
      C 270,99 285,98 295,92
      C 305,85 320,80 340,82
      C 365,86 390,95 415,99
      C 435,102 455,103 475,104
      C 495,103 506,101 506,101
      C 495,135 484,170 478,200
      C 470,225 462,250 455,275
      L 450,280
      C 415,288 370,290 320,285
      C 240,280 160,278 80,277
      L 0,277
      L 0,70
      Z
    " />
    <path class="coast" d="
      M 0,277 C 80,277 160,278 240,280 C 320,285 370,290 415,288 L 450,280 L 455,275
      C 462,250 470,225 478,200 C 484,170 495,135 506,101
      C 495,103 475,104 455,103 C 435,102 415,99 390,95
      C 365,86 340,82 320,80 C 305,85 295,92 285,98
      C 270,99 250,95 215,90 C 175,82 130,78 80,75 C 30,72 0,70 0,70
    " />

    <!-- ========== CYPRUS (clearer island in Mediterranean) ========== -->
    <ellipse class="land" cx="395" cy="148" rx="20" ry="6" />
    <path class="coast" d="M 376,150 Q 395,142 414,150 Q 395,156 376,150 Z" />

    <!-- ========== CRETE (more visible) ========== -->
    <ellipse class="land" cx="100" cy="138" rx="35" ry="5" />
    <path class="coast" d="M 65,140 Q 100,131 135,140 Q 100,145 65,140 Z" />

    <!-- ========== BLACK SEA hint (mostly off-frame top, narrow strip near top edge) ========== -->
    <path class="water" d="
      M 660,0 L 1000,0 L 1000,40
      C 920,42 850,40 780,32
      C 720,25 680,15 660,8 Z
    " />

    <!-- ========== GULF OF SUEZ (between Egypt and Sinai) ========== -->
    <path class="water" d="
      M 365,316 L 385,318 L 395,355 L 405,395 L 412,420 L 405,425 L 395,402 L 380,360 L 365,316 Z
    " />

    <!-- ========== GULF OF AQABA (between Sinai and Arabia) ========== -->
    <path class="water" d="
      M 442,326 L 462,322 L 467,358 L 458,395 L 442,425 L 432,420 L 432,395 L 442,360 L 442,326 Z
    " />

    <!-- ========== RED SEA (south of Sinai, off-frame bottom) ========== -->
    <path class="water" d="
      M 405,425 L 412,420 L 432,425 L 442,427 L 460,435 L 488,460 L 520,500 L 540,540 L 405,540 Z
    " />

    <!-- ========== PERSIAN GULF ========== -->
    <!-- North coast: long curve from where Tigris+Euphrates meet (x~860, y~290)
         eastward and southward to off-frame at bottom-right. -->
    <path class="water" d="
      M 855,295
      C 870,310 890,330 910,348
      C 935,372 955,395 975,420
      C 985,440 985,470 970,495
      L 990,540
      L 1000,540
      L 1000,280
      C 970,285 920,290 855,295
      Z
    " />
    <path class="coast" d="
      M 855,295 C 870,310 890,330 910,348 C 935,372 955,395 975,420 C 985,440 985,470 970,495
    " />

    <!-- ========== CASPIAN SEA hint (right edge) ========== -->
    <path class="water" d="
      M 985,40 L 1000,40 L 1000,250 L 990,248 C 985,180 982,110 985,40 Z
    " />

    <!-- ========== DEAD SEA ========== -->
    <ellipse class="water" cx="482" cy="263" rx="3.5" ry="13" />

    <!-- ========== SEA OF GALILEE ========== -->
    <ellipse class="water" cx="485" cy="223" rx="3" ry="5" />

    <!-- ========== NILE RIVER ========== -->
    <path class="water-line" d="M 322,540 C 320,470 314,400 308,340 C 304,310 312,290 327,288" />
    <!-- Delta forks -->
    <path class="water-line" d="M 327,288 L 318,278" />
    <path class="water-line" d="M 327,288 L 333,278" />
    <path class="water-line" d="M 327,288 L 348,279" />

    <!-- ========== JORDAN RIVER ========== -->
    <path class="water-line" d="M 485,228 C 484,235 483,245 482,250" />

    <!-- ========== TIGRIS ========== -->
    <path class="water-line" d="M 745,80 C 765,140 790,200 815,250 C 840,285 865,300 870,290" />

    <!-- ========== EUPHRATES ========== -->
    <path class="water-line" d="M 580,55 C 620,120 680,180 740,235 C 800,275 855,295 870,290" />

    <!-- ============ REGION LABELS ============ -->
    <text class="region-label" x="290" y="380">Egypt</text>
    <text class="region-label" x="408" y="365">Sinai</text>
    <text class="region-label" x="525" y="415">Arabia</text>
    <text class="region-label kanaan" x="430" y="240">Kanaan</text>
    <text class="region-label" x="510" y="280">Moab</text>
    <text class="region-label" x="525" y="160">Syria</text>
    <text class="region-label" x="690" y="155">Mesopotamia</text>
    <text class="region-label" x="820" y="220">Babylonia</text>
    <text class="region-label" x="455" y="50">Anatolia</text>
    <text class="region-label" x="50" y="55">Hellas</text>
    <text class="region-label" x="920" y="190">Persia</text>

    <!-- ============ WATER LABELS ============ -->
    <text class="water-label" x="220" y="170">Middelhavet</text>
    <text class="water-label" x="455" y="510" transform="rotate(75 455 510)">Rødehavet</text>
    <text class="water-label" x="890" y="430" transform="rotate(-52 890 430)">Persiske gulf</text>
    <text class="water-label" x="990" y="160" transform="rotate(-90 990 160)">Kaspia</text>
    <text class="water-label" x="780" y="22">Svartehavet</text>
  `;

  function render(svgEl, options) {
    options = options || {};
    svgEl.setAttribute("viewBox", options.viewBox || "0 0 1000 540");
    if (options.preserveAspectRatio) {
      svgEl.setAttribute("preserveAspectRatio", options.preserveAspectRatio);
    }
    // Inject geography at the start so markers (added later) render on top.
    svgEl.insertAdjacentHTML("afterbegin", GEO_SVG);
  }

  function parseVB(s) {
    const p = String(s).trim().split(/\s+/).map(Number);
    return { x: p[0], y: p[1], w: p[2], h: p[3] };
  }

  /**
   * Attach pan + zoom + pinch + dblclick + keyboard to an SVG element.
   * @param {SVGSVGElement} svgEl  — the .map-svg element
   * @param {object} options
   *   onChange(vb)       — called whenever viewBox changes (cheap; for scale/CSS updates)
   *   onChangeDebounced(vb) — called after viewBox settles (~100ms; for collision detection)
   *   minViewBoxWidth    — min zoom-in width (default 60)
   *   maxViewBoxWidth    — max zoom-out width (default fullVB.w * 1.2)
   * @returns {object} controller — { zoomBy, reset, zoomToLocation, getViewBox }
   */
  function attachInteraction(svgEl, options) {
    options = options || {};
    const FULL_VB = parseVB(svgEl.getAttribute("viewBox") || "0 0 1000 540");
    let currentVB = { ...FULL_VB };

    const MIN_W = options.minViewBoxWidth || 60;
    const MAX_W = options.maxViewBoxWidth || FULL_VB.w * 1.2;

    let debounceTimer = null;
    function applyVB() {
      svgEl.setAttribute("viewBox",
        currentVB.x + " " + currentVB.y + " " + currentVB.w + " " + currentVB.h);
      if (options.onChange) options.onChange(currentVB);
      if (options.onChangeDebounced) {
        clearTimeout(debounceTimer);
        debounceTimer = setTimeout(() => options.onChangeDebounced(currentVB), 100);
      }
    }

    function clientToSvgPoint(clientX, clientY) {
      const pt = svgEl.createSVGPoint();
      pt.x = clientX; pt.y = clientY;
      return pt.matrixTransform(svgEl.getScreenCTM().inverse());
    }

    function zoomBy(factor, centerClientX, centerClientY) {
      const newW = currentVB.w * factor;
      if (newW < MIN_W || newW > MAX_W) return;
      let cx, cy;
      if (centerClientX != null) {
        const sp = clientToSvgPoint(centerClientX, centerClientY);
        cx = sp.x; cy = sp.y;
      } else {
        cx = currentVB.x + currentVB.w / 2;
        cy = currentVB.y + currentVB.h / 2;
      }
      currentVB.x = cx - (cx - currentVB.x) * factor;
      currentVB.y = cy - (cy - currentVB.y) * factor;
      currentVB.w = newW;
      currentVB.h = currentVB.h * factor;
      applyVB();
    }

    function reset() {
      currentVB = { ...FULL_VB };
      applyVB();
    }

    function zoomToLocation(loc, w) {
      const targetW = w || (FULL_VB.w * 0.2);
      const targetH = targetW * (FULL_VB.h / FULL_VB.w);
      currentVB = {
        x: loc.x - targetW / 2,
        y: loc.y - targetH / 2,
        w: targetW,
        h: targetH
      };
      applyVB();
    }

    // Wheel zoom around cursor
    svgEl.addEventListener("wheel", (e) => {
      e.preventDefault();
      zoomBy(e.deltaY > 0 ? 1.18 : 1 / 1.18, e.clientX, e.clientY);
    }, { passive: false });

    // Pointer-based pan + pinch
    const pointers = new Map();
    let dragState = null;
    let pinchState = null;

    function pointerDistance(pts) {
      const dx = pts[0].x - pts[1].x, dy = pts[0].y - pts[1].y;
      return Math.hypot(dx, dy);
    }
    function pointerMidpoint(pts) {
      return { x: (pts[0].x + pts[1].x) / 2, y: (pts[0].y + pts[1].y) / 2 };
    }

    svgEl.addEventListener("pointerdown", (e) => {
      // Don't intercept marker/interactive children
      if (e.target.closest && e.target.closest(".place-marker, .marker-ring, .marker-num, .marker-label, .place-dot")) {
        return;
      }
      svgEl.setPointerCapture(e.pointerId);
      pointers.set(e.pointerId, { x: e.clientX, y: e.clientY });

      if (pointers.size === 1) {
        svgEl.classList.add("dragging");
        dragState = {
          sx: e.clientX, sy: e.clientY,
          vbx: currentVB.x, vby: currentVB.y
        };
      } else if (pointers.size === 2) {
        dragState = null;
        svgEl.classList.remove("dragging");
        const pts = [...pointers.values()];
        const mid = pointerMidpoint(pts);
        pinchState = {
          startDist: pointerDistance(pts),
          startVB: { ...currentVB },
          center: clientToSvgPoint(mid.x, mid.y)
        };
      }
    });
    svgEl.addEventListener("pointermove", (e) => {
      if (pointers.has(e.pointerId)) {
        pointers.set(e.pointerId, { x: e.clientX, y: e.clientY });
      }
      if (pinchState && pointers.size === 2) {
        const pts = [...pointers.values()];
        const dist = pointerDistance(pts);
        if (!dist) return;
        const factor = pinchState.startDist / dist;
        const newW = pinchState.startVB.w * factor;
        if (newW < MIN_W || newW > MAX_W) return;
        currentVB.x = pinchState.center.x - (pinchState.center.x - pinchState.startVB.x) * factor;
        currentVB.y = pinchState.center.y - (pinchState.center.y - pinchState.startVB.y) * factor;
        currentVB.w = newW;
        currentVB.h = pinchState.startVB.h * factor;
        applyVB();
        return;
      }
      if (dragState && pointers.size === 1) {
        const rect = svgEl.getBoundingClientRect();
        const dx = (e.clientX - dragState.sx) * (currentVB.w / rect.width);
        const dy = (e.clientY - dragState.sy) * (currentVB.h / rect.height);
        currentVB.x = dragState.vbx - dx;
        currentVB.y = dragState.vby - dy;
        applyVB();
      }
    });
    function endPointer(e) {
      if (pointers.has(e.pointerId)) pointers.delete(e.pointerId);
      if (pointers.size < 2) pinchState = null;
      if (pointers.size === 0) {
        dragState = null;
        svgEl.classList.remove("dragging");
      }
      try { svgEl.releasePointerCapture(e.pointerId); } catch (_) {}
    }
    svgEl.addEventListener("pointerup", endPointer);
    svgEl.addEventListener("pointercancel", endPointer);
    svgEl.addEventListener("pointerleave", endPointer);

    // Double-click / double-tap → zoom in 2x (Shift = zoom out)
    svgEl.addEventListener("dblclick", (e) => {
      if (e.target.closest && e.target.closest(".place-marker, .place-dot")) return;
      e.preventDefault();
      zoomBy(e.shiftKey ? 2 : 0.5, e.clientX, e.clientY);
    });

    // Block native pinch on touch (we handle it)
    svgEl.addEventListener("touchstart", (e) => {
      if (e.touches.length > 1) e.preventDefault();
    }, { passive: false });
    svgEl.addEventListener("touchmove", (e) => {
      if (e.touches.length > 1) e.preventDefault();
    }, { passive: false });

    // Keyboard
    function onKey(e) {
      if (e.target && /^(INPUT|TEXTAREA|SELECT)$/.test(e.target.tagName)) return;
      if (e.key === "+" || e.key === "=") { zoomBy(1 / 1.3); }
      else if (e.key === "-" || e.key === "_") { zoomBy(1.3); }
      else if (e.key === "0") { reset(); }
    }
    window.addEventListener("keydown", onKey);

    // Initial fire so consumers can compute scale on mount
    requestAnimationFrame(() => {
      if (options.onChange) options.onChange(currentVB);
      if (options.onChangeDebounced) options.onChangeDebounced(currentVB);
    });

    return {
      zoomBy: zoomBy,
      reset: reset,
      zoomToLocation: zoomToLocation,
      getViewBox: () => ({ ...currentVB }),
      getFullViewBox: () => ({ ...FULL_VB }),
      destroy: () => window.removeEventListener("keydown", onKey)
    };
  }

  /**
   * Compute scale factor for the SVG (viewBox.w / rendered.w, max with vertical).
   * Used to set --map-scale CSS variable for consistent screen-px sizing.
   */
  function computeScale(svgEl) {
    const vb = svgEl.viewBox && svgEl.viewBox.baseVal;
    const rect = svgEl.getBoundingClientRect();
    if (!vb || !vb.width || !rect.width || !rect.height) return 1;
    return Math.max(vb.width / rect.width, vb.height / rect.height);
  }

  /**
   * Compute "region fade" opacity based on current vs full viewBox width.
   * Smooth fade so timeline pages (ratio ~0.3) still show region context.
   *   ratio >= 0.5 → 0.65 (full)
   *   ratio <= 0.05 → 0 (invisible at single-city zoom)
   *   linear in between
   */
  function computeRegionFade(currentW, fullW) {
    const ratio = currentW / fullW;
    const t = (ratio - 0.05) / (0.5 - 0.05);
    return Math.max(0, Math.min(0.65, t * 0.65));
  }

  /**
   * Hide overlapping place labels. Priority: places with `pages` win.
   */
  function applyLabelCollision(svgEl) {
    const labels = [...svgEl.querySelectorAll(".place-label-soft")];
    labels.forEach(l => l.classList.remove("collide-hidden"));
    // Sort: has-pages first, then alphabetical for stable order
    labels.sort((a, b) => {
      const aId = a.getAttribute("data-loc"), bId = b.getAttribute("data-loc");
      const aLoc = LOCATIONS[aId], bLoc = LOCATIONS[bId];
      const aHas = !!(aLoc && aLoc.pages && aLoc.pages.length);
      const bHas = !!(bLoc && bLoc.pages && bLoc.pages.length);
      if (aHas !== bHas) return bHas - aHas;
      return aId < bId ? -1 : 1;
    });
    const visible = [];
    labels.forEach(l => {
      const bb = l.getBoundingClientRect();
      if (!bb.width || !bb.height) return;
      // Add small margin
      const m = 2;
      const expanded = {
        left: bb.left - m, right: bb.right + m,
        top: bb.top - m, bottom: bb.bottom + m
      };
      const collides = visible.some(v =>
        expanded.left < v.right && expanded.right > v.left &&
        expanded.top < v.bottom && expanded.bottom > v.top
      );
      if (collides) l.classList.add("collide-hidden");
      else visible.push(expanded);
    });
  }

  global.BibelAtlas = {
    fullViewBox: "0 0 1000 540",
    locations: LOCATIONS,
    geoSvg: GEO_SVG,
    render: render,
    attachInteraction: attachInteraction,
    computeScale: computeScale,
    computeRegionFade: computeRegionFade,
    applyLabelCollision: applyLabelCollision
  };
})(window);
