#!/usr/bin/env node
/**
 * build-data.js — generate maps/locations.js from maps/locations.json + scan
 * all *-tidslinje.html files for `locations: ["id1", "id2"]` references.
 *
 * Usage:
 *   node scripts/build-data.js
 *   npm run build
 *
 * Workflow:
 *   1. Edit maps/locations.json to add/modify locations (single source of truth)
 *   2. Edit *-tidslinje.html files to add `locations: [...]` per phase
 *   3. Run this script — it auto-merges page references into each location's
 *      `pages` array, then writes the result to maps/locations.js
 *   4. Pages include locations.js BEFORE bibel-atlas.js
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const SRC_JSON = path.join(ROOT, 'maps/locations.json');
const OUT_JS   = path.join(ROOT, 'maps/locations.js');

function readTimelineFiles() {
  return fs.readdirSync(ROOT)
    .filter(f => /-tidslinje\.html$/.test(f))
    .map(f => ({ name: f, path: path.join(ROOT, f) }));
}

function extractLocationRefs(html) {
  const refs = [];
  const matches = html.matchAll(/locations\s*:\s*\[([^\]]*)\]/g);
  for (const m of matches) {
    const idMatches = m[1].matchAll(/["']([a-zA-Z0-9_-]+)["']/g);
    for (const im of idMatches) refs.push(im[1]);
  }
  return refs;
}

function main() {
  const locations = JSON.parse(fs.readFileSync(SRC_JSON, 'utf8'));

  const reverseIndex = {};
  const timelineFiles = readTimelineFiles();
  timelineFiles.forEach(({ name, path: filepath }) => {
    const html = fs.readFileSync(filepath, 'utf8');
    const refs = extractLocationRefs(html);
    refs.forEach(id => {
      if (!reverseIndex[id]) reverseIndex[id] = new Set();
      reverseIndex[id].add(name);
    });
  });

  let autoCount = 0;
  const warnings = [];
  Object.keys(locations).forEach(id => {
    const auto = reverseIndex[id];
    const manual = new Set(locations[id].pages || []);
    if (auto) auto.forEach(p => manual.add(p));
    if (manual.size > 0) {
      locations[id].pages = Array.from(manual).sort();
      autoCount += auto ? auto.size : 0;
    }
  });

  Object.keys(reverseIndex).forEach(id => {
    if (!locations[id]) {
      warnings.push('Location "' + id + '" referenced in ' + [...reverseIndex[id]].join(', ') + ' but not in locations.json');
    }
  });

  const banner = [
    '/* AUTO-GENERATED by scripts/build-data.js — do not edit directly. */',
    '/* Source: maps/locations.json + locations: [...] arrays in *-tidslinje.html */',
    '/* Run `npm run build` after editing either source. */',
    ''
  ].join('\n');
  const body = 'window.__BIBEL_LOCATIONS = ' + JSON.stringify(locations, null, 2) + ';\n';
  fs.writeFileSync(OUT_JS, banner + body);

  console.log(Object.keys(locations).length + ' locations -> ' + path.relative(ROOT, OUT_JS));
  console.log(autoCount + ' auto-derived page references from ' + timelineFiles.length + ' tidslinje files');
  if (warnings.length) {
    console.log('');
    warnings.forEach(w => console.log('WARN: ' + w));
    process.exitCode = 1;
  }
}

main();
